// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDihmi2w6Nsr-CoM3BEucJHaRKC4ZWF82c',
    appId: '1:625558584967:web:12ae95f3aeef1c3c04c222',
    messagingSenderId: '625558584967',
    projectId: 'adhicine-e52e7',
    authDomain: 'adhicine-e52e7.firebaseapp.com',
    storageBucket: 'adhicine-e52e7.firebasestorage.app',
    measurementId: 'G-GLS8Z5CYFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjYz7Mgct-tn-0rw9vttPP4Qp3VqbbfVI',
    appId: '1:625558584967:android:36bbb4594ed9ba6404c222',
    messagingSenderId: '625558584967',
    projectId: 'adhicine-e52e7',
    storageBucket: 'adhicine-e52e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL9sgDi-iobR0Tn-EbkbZcKdSBTHxh448',
    appId: '1:625558584967:ios:e5cd139e15a7677004c222',
    messagingSenderId: '625558584967',
    projectId: 'adhicine-e52e7',
    storageBucket: 'adhicine-e52e7.firebasestorage.app',
    iosBundleId: 'com.example.adhicine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL9sgDi-iobR0Tn-EbkbZcKdSBTHxh448',
    appId: '1:625558584967:ios:e5cd139e15a7677004c222',
    messagingSenderId: '625558584967',
    projectId: 'adhicine-e52e7',
    storageBucket: 'adhicine-e52e7.firebasestorage.app',
    iosBundleId: 'com.example.adhicine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDihmi2w6Nsr-CoM3BEucJHaRKC4ZWF82c',
    appId: '1:625558584967:web:114c3c6c69b3a97404c222',
    messagingSenderId: '625558584967',
    projectId: 'adhicine-e52e7',
    authDomain: 'adhicine-e52e7.firebaseapp.com',
    storageBucket: 'adhicine-e52e7.firebasestorage.app',
    measurementId: 'G-BF7XNWJG7Y',
  );
}
